### ISSUE TITLE
使用this.$parentevent实现子组件调用父组件方法遇到的问题

### ISSUE THREAD

**Issue by yanpingYANPING** [WEB-qq-635678224/JS-Note#10]
子组件调用父组件的方法this.$parent.deptTreeState()报错
![微信图片_20190903170202.png](https://i.loli.net/2019/09/03/PGuprETBnio9W15.png)
原因：由于vue层层封装，它爹早就不是它爹了，很难找到它爹，所以这个方法有坑啊！！！
![6b3855ddc5142c46cf08f330723166c.png](https://i.loli.net/2019/09/03/QXJzuWUELvFtZ4p.png)
找了很多层parent，终于找到了deptTreeState()

**Comment by Lee981265** [comment]
萍姐实力坑爹

**Comment by smallmonsters** [comment]
嵌套这么多层，可以用inheritAttrs + $attrs + $listeners
