### ISSUE TITLE
v-slot 解构赋值

### ISSUE THREAD

**Issue by yanpingYANPING** [WEB-qq-635678224/JS-Note#11]
这是子组件
![570e0aed86bf090a8898c4c7b6463ab.png](https://i.loli.net/2019/09/19/94Pqc7HToWgnFLB.png)
这是父组件
![daca12d5c54fc1844553ebb1fbd52b9.png](https://i.loli.net/2019/09/19/yzP9NpUiSe8nZqu.png)

1  报错原因分析："vue": "^2.5.2"，可能是vue低于2.6.0版本，但是后面vue升级为"vue": "^2.6.10"还是报错
2 解构赋值的写法有问题
总结：最后还是没找出真正的报错原因

**Comment by Lee981265** [comment]
![image.png](https://img.hacpai.com/file/2019/09/image-9c6f1a4b.png)

**Comment by yanpingYANPING** [comment]
好猫！！！ 优秀的毛毛的好猫猫
