### ISSUE TITLE
关于如何使用这个仓库的一些问题

### ISSUE THREAD

**Issue by smallmonsters** [WEB-qq-635678224/JS-Note#6]
对于一个使用GitHub不熟悉的人，在加入这个“组织”后有些不懂的地方，总结了一下几点
1、对于别人的仓库是不是不能直接pull=》修改=》push 。
2、这个组织是任何人都能拉人吗？我们要怎么拉别人进入呢
3、md文件没有有效的书写方法吗？比如我写个标题就要使用# title 这样吗，这比较麻烦吧，

**Comment by Lee981265** [comment]
- 只有管理员才可以操作别人的仓库
- 只有管理员才能拉人
- md书写有教程 当然你也可以直接写字符串

**Comment by Lee981265** [comment]
[关于markdown书写](https://github.com/Lee981265/Free-Style/blob/master/Markdown.md)

**Comment by Lee981265** [comment]
如果你要拉人我可以给你管理员权限

**Comment by guohuihot** [comment]
1. 可以pull->修改->push（简称pr）, 但是需要管理员验证后才可以merge到当前分支，如果是管理可以自己操作
